add_newline = true
scan_timeout = 10

format = """
(fg:#fff1cf)$username$directory$git_branch$git_status$time$shell$character"""

[line_break]
disabled = false

[fill]
symbol = " "
style = "fg:#252525 bg:#6f6565"

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"

[time]
format = '[\[$time\] ](fg:#fff1cf bg:#6f6565)'
utc_time_offset = "local"
time_format = "%T"
disabled = false
time_range = "-"

[git_branch]
format = "[$symbol$branch](bg:#252525)[ ](fg:#252525 bg:#6f6565 bold)"
symbol = " "

[shell]
bash_indicator = "[](fg:#c4c431 bg:#6f6565)[BSH-MODE](fg:#fff1cf bg:#c4c431)[](fg:#c4c431 bg:#6f6565)[  ](fg:#c4c431 bg:#6f6565)[](fg:#6f6565)"
zsh_indicator = "[](fg:#94b3a8 bg:#6f6565)[ZSH-MODE](fg:#fff1cf bg:#94b3a8)[](fg:#94b3a8 bg:#6f6565)[  ](fg:#94b3a8 bg:#6f6565)[](fg:#6f6565)"
unknown_indicator = "[](fg:#fff1cf bg:#6f6565)[???-MODE][](fg:#6f6565)"
style = "fg:#fff1cf bg:#6f6565"
disabled = false

[directory]
format = "[$path]($style)[$read_only](fg:#fff bg:#6f6565)[ ](fg:#6f6565 bg:#252525 bold)"
style = "fg:#fff1cf bg:#6f6565"
truncation_symbol = "…/"
truncate_to_repo = false
truncation_length = 100
home_symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]](fg:#fff1cf bg:#6f6565)[ ](fg:#fff1cf bg:#6f6565))'

[username]
format = "[](fg:#fff1cf bold)[ ](fg:#252525 bg:#fff1cf bold)[ ](fg:#fff1cf bg:#6f6565 bold)"
show_always = true
disabled = false
